/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkersRouteImport } from './routes/workers'
import { Route as UtilitiesRouteImport } from './routes/utilities'
import { Route as TeachersRouteImport } from './routes/teachers'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as NoticesRouteImport } from './routes/notices'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as IspRouteImport } from './routes/isp'
import { Route as HelplineRouteImport } from './routes/helpline'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CvBuilderRouteImport } from './routes/cv-builder'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkersIndexRouteImport } from './routes/workers.index'
import { Route as TeachersIndexRouteImport } from './routes/teachers.index'
import { Route as BusinessIndexRouteImport } from './routes/business.index'
import { Route as WorkersRegisterRouteImport } from './routes/workers.register'
import { Route as WorkersIdRouteImport } from './routes/workers.$id'
import { Route as TeachersTuitionsRouteImport } from './routes/teachers.tuitions'
import { Route as TeachersResourcesRouteImport } from './routes/teachers.resources'
import { Route as TeachersRegisterRouteImport } from './routes/teachers.register'
import { Route as TeachersNewsRouteImport } from './routes/teachers.news'
import { Route as TeachersAchievementsRouteImport } from './routes/teachers.achievements'
import { Route as TeachersIdRouteImport } from './routes/teachers.$id'
import { Route as BusinessRegisterRouteImport } from './routes/business.register'
import { Route as BusinessDirectoryRouteImport } from './routes/business.directory'
import { Route as BusinessSlugRouteImport } from './routes/business.$slug'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedMyBusinessRouteImport } from './routes/_authenticated/my-business'
import { Route as AuthenticatedInsightsRouteImport } from './routes/_authenticated/insights'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCompareRouteImport } from './routes/_authenticated/compare'
import { Route as AuthenticatedBillsRouteImport } from './routes/_authenticated/bills'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as TeachersTuitionsIndexRouteImport } from './routes/teachers.tuitions.index'
import { Route as TeachersNewsIndexRouteImport } from './routes/teachers.news.index'
import { Route as TeachersAchievementsIndexRouteImport } from './routes/teachers.achievements.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as TeachersTuitionsNewRouteImport } from './routes/teachers.tuitions.new'
import { Route as TeachersTuitionsIdRouteImport } from './routes/teachers.tuitions.$id'
import { Route as TeachersNewsIdRouteImport } from './routes/teachers.news.$id'
import { Route as TeachersAchievementsIdRouteImport } from './routes/teachers.achievements.$id'
import { Route as ApiPublicStatsRouteImport } from './routes/api/public/stats'
import { Route as ApiPublicAnnouncementsRouteImport } from './routes/api/public/announcements'
import { Route as AuthenticatedBillsNewRouteImport } from './routes/_authenticated/bills.new'
import { Route as AuthenticatedAdminWorkersRouteImport } from './routes/_authenticated/admin.workers'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminTuitionRequestsRouteImport } from './routes/_authenticated/admin.tuition-requests'
import { Route as AuthenticatedAdminTuitionApplicationsRouteImport } from './routes/_authenticated/admin.tuition-applications'
import { Route as AuthenticatedAdminTeachersRouteImport } from './routes/_authenticated/admin.teachers'
import { Route as AuthenticatedAdminStudyResourcesRouteImport } from './routes/_authenticated/admin.study-resources'
import { Route as AuthenticatedAdminEducationNewsRouteImport } from './routes/_authenticated/admin.education-news'
import { Route as AuthenticatedAdminComplaintsRouteImport } from './routes/_authenticated/admin.complaints'
import { Route as AuthenticatedAdminBusinessesRouteImport } from './routes/_authenticated/admin.businesses'
import { Route as AuthenticatedAdminBusinessReviewsRouteImport } from './routes/_authenticated/admin.business-reviews'
import { Route as AuthenticatedAdminBusinessCategoriesRouteImport } from './routes/_authenticated/admin.business-categories'
import { Route as AuthenticatedAdminBillsRouteImport } from './routes/_authenticated/admin.bills'
import { Route as AuthenticatedAdminAnnouncementsRouteImport } from './routes/_authenticated/admin.announcements'
import { Route as AuthenticatedAdminAchievementsRouteImport } from './routes/_authenticated/admin.achievements'
import { Route as AuthenticatedBillsIdEditRouteImport } from './routes/_authenticated/bills.$id.edit'

const WorkersRoute = WorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => rootRouteImport,
} as any)
const UtilitiesRoute = UtilitiesRouteImport.update({
  id: '/utilities',
  path: '/utilities',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachersRoute = TeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticesRoute = NoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const IspRoute = IspRouteImport.update({
  id: '/isp',
  path: '/isp',
  getParentRoute: () => rootRouteImport,
} as any)
const HelplineRoute = HelplineRouteImport.update({
  id: '/helpline',
  path: '/helpline',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CvBuilderRoute = CvBuilderRouteImport.update({
  id: '/cv-builder',
  path: '/cv-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkersIndexRoute = WorkersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkersRoute,
} as any)
const TeachersIndexRoute = TeachersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeachersRoute,
} as any)
const BusinessIndexRoute = BusinessIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BusinessRoute,
} as any)
const WorkersRegisterRoute = WorkersRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => WorkersRoute,
} as any)
const WorkersIdRoute = WorkersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => WorkersRoute,
} as any)
const TeachersTuitionsRoute = TeachersTuitionsRouteImport.update({
  id: '/tuitions',
  path: '/tuitions',
  getParentRoute: () => TeachersRoute,
} as any)
const TeachersResourcesRoute = TeachersResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => TeachersRoute,
} as any)
const TeachersRegisterRoute = TeachersRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => TeachersRoute,
} as any)
const TeachersNewsRoute = TeachersNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => TeachersRoute,
} as any)
const TeachersAchievementsRoute = TeachersAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => TeachersRoute,
} as any)
const TeachersIdRoute = TeachersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TeachersRoute,
} as any)
const BusinessRegisterRoute = BusinessRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessDirectoryRoute = BusinessDirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessSlugRoute = BusinessSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BusinessRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyBusinessRoute = AuthenticatedMyBusinessRouteImport.update({
  id: '/my-business',
  path: '/my-business',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInsightsRoute = AuthenticatedInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompareRoute = AuthenticatedCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillsRoute = AuthenticatedBillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const TeachersTuitionsIndexRoute = TeachersTuitionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeachersTuitionsRoute,
} as any)
const TeachersNewsIndexRoute = TeachersNewsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeachersNewsRoute,
} as any)
const TeachersAchievementsIndexRoute =
  TeachersAchievementsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => TeachersAchievementsRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const TeachersTuitionsNewRoute = TeachersTuitionsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => TeachersTuitionsRoute,
} as any)
const TeachersTuitionsIdRoute = TeachersTuitionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TeachersTuitionsRoute,
} as any)
const TeachersNewsIdRoute = TeachersNewsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TeachersNewsRoute,
} as any)
const TeachersAchievementsIdRoute = TeachersAchievementsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TeachersAchievementsRoute,
} as any)
const ApiPublicStatsRoute = ApiPublicStatsRouteImport.update({
  id: '/api/public/stats',
  path: '/api/public/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAnnouncementsRoute = ApiPublicAnnouncementsRouteImport.update({
  id: '/api/public/announcements',
  path: '/api/public/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBillsNewRoute = AuthenticatedBillsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedBillsRoute,
} as any)
const AuthenticatedAdminWorkersRoute =
  AuthenticatedAdminWorkersRouteImport.update({
    id: '/workers',
    path: '/workers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminTuitionRequestsRoute =
  AuthenticatedAdminTuitionRequestsRouteImport.update({
    id: '/tuition-requests',
    path: '/tuition-requests',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTuitionApplicationsRoute =
  AuthenticatedAdminTuitionApplicationsRouteImport.update({
    id: '/tuition-applications',
    path: '/tuition-applications',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTeachersRoute =
  AuthenticatedAdminTeachersRouteImport.update({
    id: '/teachers',
    path: '/teachers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminStudyResourcesRoute =
  AuthenticatedAdminStudyResourcesRouteImport.update({
    id: '/study-resources',
    path: '/study-resources',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEducationNewsRoute =
  AuthenticatedAdminEducationNewsRouteImport.update({
    id: '/education-news',
    path: '/education-news',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminComplaintsRoute =
  AuthenticatedAdminComplaintsRouteImport.update({
    id: '/complaints',
    path: '/complaints',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBusinessesRoute =
  AuthenticatedAdminBusinessesRouteImport.update({
    id: '/businesses',
    path: '/businesses',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBusinessReviewsRoute =
  AuthenticatedAdminBusinessReviewsRouteImport.update({
    id: '/business-reviews',
    path: '/business-reviews',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBusinessCategoriesRoute =
  AuthenticatedAdminBusinessCategoriesRouteImport.update({
    id: '/business-categories',
    path: '/business-categories',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBillsRoute = AuthenticatedAdminBillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAnnouncementsRoute =
  AuthenticatedAdminAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAchievementsRoute =
  AuthenticatedAdminAchievementsRouteImport.update({
    id: '/achievements',
    path: '/achievements',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedBillsIdEditRoute =
  AuthenticatedBillsIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => AuthenticatedBillsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/business': typeof BusinessRouteWithChildren
  '/calculator': typeof CalculatorRoute
  '/cv-builder': typeof CvBuilderRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/helpline': typeof HelplineRoute
  '/isp': typeof IspRoute
  '/legal': typeof LegalRoute
  '/notices': typeof NoticesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/stats': typeof StatsRoute
  '/teachers': typeof TeachersRouteWithChildren
  '/utilities': typeof UtilitiesRoute
  '/workers': typeof WorkersRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/bills': typeof AuthenticatedBillsRouteWithChildren
  '/compare': typeof AuthenticatedCompareRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/my-business': typeof AuthenticatedMyBusinessRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/business/$slug': typeof BusinessSlugRoute
  '/business/directory': typeof BusinessDirectoryRoute
  '/business/register': typeof BusinessRegisterRoute
  '/teachers/$id': typeof TeachersIdRoute
  '/teachers/achievements': typeof TeachersAchievementsRouteWithChildren
  '/teachers/news': typeof TeachersNewsRouteWithChildren
  '/teachers/register': typeof TeachersRegisterRoute
  '/teachers/resources': typeof TeachersResourcesRoute
  '/teachers/tuitions': typeof TeachersTuitionsRouteWithChildren
  '/workers/$id': typeof WorkersIdRoute
  '/workers/register': typeof WorkersRegisterRoute
  '/business/': typeof BusinessIndexRoute
  '/teachers/': typeof TeachersIndexRoute
  '/workers/': typeof WorkersIndexRoute
  '/admin/achievements': typeof AuthenticatedAdminAchievementsRoute
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/bills': typeof AuthenticatedAdminBillsRoute
  '/admin/business-categories': typeof AuthenticatedAdminBusinessCategoriesRoute
  '/admin/business-reviews': typeof AuthenticatedAdminBusinessReviewsRoute
  '/admin/businesses': typeof AuthenticatedAdminBusinessesRoute
  '/admin/complaints': typeof AuthenticatedAdminComplaintsRoute
  '/admin/education-news': typeof AuthenticatedAdminEducationNewsRoute
  '/admin/study-resources': typeof AuthenticatedAdminStudyResourcesRoute
  '/admin/teachers': typeof AuthenticatedAdminTeachersRoute
  '/admin/tuition-applications': typeof AuthenticatedAdminTuitionApplicationsRoute
  '/admin/tuition-requests': typeof AuthenticatedAdminTuitionRequestsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/workers': typeof AuthenticatedAdminWorkersRoute
  '/bills/new': typeof AuthenticatedBillsNewRoute
  '/api/public/announcements': typeof ApiPublicAnnouncementsRoute
  '/api/public/stats': typeof ApiPublicStatsRoute
  '/teachers/achievements/$id': typeof TeachersAchievementsIdRoute
  '/teachers/news/$id': typeof TeachersNewsIdRoute
  '/teachers/tuitions/$id': typeof TeachersTuitionsIdRoute
  '/teachers/tuitions/new': typeof TeachersTuitionsNewRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/teachers/achievements/': typeof TeachersAchievementsIndexRoute
  '/teachers/news/': typeof TeachersNewsIndexRoute
  '/teachers/tuitions/': typeof TeachersTuitionsIndexRoute
  '/bills/$id/edit': typeof AuthenticatedBillsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calculator': typeof CalculatorRoute
  '/cv-builder': typeof CvBuilderRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/helpline': typeof HelplineRoute
  '/isp': typeof IspRoute
  '/legal': typeof LegalRoute
  '/notices': typeof NoticesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/stats': typeof StatsRoute
  '/utilities': typeof UtilitiesRoute
  '/bills': typeof AuthenticatedBillsRouteWithChildren
  '/compare': typeof AuthenticatedCompareRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/my-business': typeof AuthenticatedMyBusinessRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/business/$slug': typeof BusinessSlugRoute
  '/business/directory': typeof BusinessDirectoryRoute
  '/business/register': typeof BusinessRegisterRoute
  '/teachers/$id': typeof TeachersIdRoute
  '/teachers/register': typeof TeachersRegisterRoute
  '/teachers/resources': typeof TeachersResourcesRoute
  '/workers/$id': typeof WorkersIdRoute
  '/workers/register': typeof WorkersRegisterRoute
  '/business': typeof BusinessIndexRoute
  '/teachers': typeof TeachersIndexRoute
  '/workers': typeof WorkersIndexRoute
  '/admin/achievements': typeof AuthenticatedAdminAchievementsRoute
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/bills': typeof AuthenticatedAdminBillsRoute
  '/admin/business-categories': typeof AuthenticatedAdminBusinessCategoriesRoute
  '/admin/business-reviews': typeof AuthenticatedAdminBusinessReviewsRoute
  '/admin/businesses': typeof AuthenticatedAdminBusinessesRoute
  '/admin/complaints': typeof AuthenticatedAdminComplaintsRoute
  '/admin/education-news': typeof AuthenticatedAdminEducationNewsRoute
  '/admin/study-resources': typeof AuthenticatedAdminStudyResourcesRoute
  '/admin/teachers': typeof AuthenticatedAdminTeachersRoute
  '/admin/tuition-applications': typeof AuthenticatedAdminTuitionApplicationsRoute
  '/admin/tuition-requests': typeof AuthenticatedAdminTuitionRequestsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/workers': typeof AuthenticatedAdminWorkersRoute
  '/bills/new': typeof AuthenticatedBillsNewRoute
  '/api/public/announcements': typeof ApiPublicAnnouncementsRoute
  '/api/public/stats': typeof ApiPublicStatsRoute
  '/teachers/achievements/$id': typeof TeachersAchievementsIdRoute
  '/teachers/news/$id': typeof TeachersNewsIdRoute
  '/teachers/tuitions/$id': typeof TeachersTuitionsIdRoute
  '/teachers/tuitions/new': typeof TeachersTuitionsNewRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/teachers/achievements': typeof TeachersAchievementsIndexRoute
  '/teachers/news': typeof TeachersNewsIndexRoute
  '/teachers/tuitions': typeof TeachersTuitionsIndexRoute
  '/bills/$id/edit': typeof AuthenticatedBillsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/business': typeof BusinessRouteWithChildren
  '/calculator': typeof CalculatorRoute
  '/cv-builder': typeof CvBuilderRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/helpline': typeof HelplineRoute
  '/isp': typeof IspRoute
  '/legal': typeof LegalRoute
  '/notices': typeof NoticesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/stats': typeof StatsRoute
  '/teachers': typeof TeachersRouteWithChildren
  '/utilities': typeof UtilitiesRoute
  '/workers': typeof WorkersRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/bills': typeof AuthenticatedBillsRouteWithChildren
  '/_authenticated/compare': typeof AuthenticatedCompareRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/insights': typeof AuthenticatedInsightsRoute
  '/_authenticated/my-business': typeof AuthenticatedMyBusinessRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/business/$slug': typeof BusinessSlugRoute
  '/business/directory': typeof BusinessDirectoryRoute
  '/business/register': typeof BusinessRegisterRoute
  '/teachers/$id': typeof TeachersIdRoute
  '/teachers/achievements': typeof TeachersAchievementsRouteWithChildren
  '/teachers/news': typeof TeachersNewsRouteWithChildren
  '/teachers/register': typeof TeachersRegisterRoute
  '/teachers/resources': typeof TeachersResourcesRoute
  '/teachers/tuitions': typeof TeachersTuitionsRouteWithChildren
  '/workers/$id': typeof WorkersIdRoute
  '/workers/register': typeof WorkersRegisterRoute
  '/business/': typeof BusinessIndexRoute
  '/teachers/': typeof TeachersIndexRoute
  '/workers/': typeof WorkersIndexRoute
  '/_authenticated/admin/achievements': typeof AuthenticatedAdminAchievementsRoute
  '/_authenticated/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/_authenticated/admin/bills': typeof AuthenticatedAdminBillsRoute
  '/_authenticated/admin/business-categories': typeof AuthenticatedAdminBusinessCategoriesRoute
  '/_authenticated/admin/business-reviews': typeof AuthenticatedAdminBusinessReviewsRoute
  '/_authenticated/admin/businesses': typeof AuthenticatedAdminBusinessesRoute
  '/_authenticated/admin/complaints': typeof AuthenticatedAdminComplaintsRoute
  '/_authenticated/admin/education-news': typeof AuthenticatedAdminEducationNewsRoute
  '/_authenticated/admin/study-resources': typeof AuthenticatedAdminStudyResourcesRoute
  '/_authenticated/admin/teachers': typeof AuthenticatedAdminTeachersRoute
  '/_authenticated/admin/tuition-applications': typeof AuthenticatedAdminTuitionApplicationsRoute
  '/_authenticated/admin/tuition-requests': typeof AuthenticatedAdminTuitionRequestsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/workers': typeof AuthenticatedAdminWorkersRoute
  '/_authenticated/bills/new': typeof AuthenticatedBillsNewRoute
  '/api/public/announcements': typeof ApiPublicAnnouncementsRoute
  '/api/public/stats': typeof ApiPublicStatsRoute
  '/teachers/achievements/$id': typeof TeachersAchievementsIdRoute
  '/teachers/news/$id': typeof TeachersNewsIdRoute
  '/teachers/tuitions/$id': typeof TeachersTuitionsIdRoute
  '/teachers/tuitions/new': typeof TeachersTuitionsNewRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/teachers/achievements/': typeof TeachersAchievementsIndexRoute
  '/teachers/news/': typeof TeachersNewsIndexRoute
  '/teachers/tuitions/': typeof TeachersTuitionsIndexRoute
  '/_authenticated/bills/$id/edit': typeof AuthenticatedBillsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/business'
    | '/calculator'
    | '/cv-builder'
    | '/forgot-password'
    | '/helpline'
    | '/isp'
    | '/legal'
    | '/notices'
    | '/reset-password'
    | '/stats'
    | '/teachers'
    | '/utilities'
    | '/workers'
    | '/admin'
    | '/bills'
    | '/compare'
    | '/dashboard'
    | '/insights'
    | '/my-business'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/business/$slug'
    | '/business/directory'
    | '/business/register'
    | '/teachers/$id'
    | '/teachers/achievements'
    | '/teachers/news'
    | '/teachers/register'
    | '/teachers/resources'
    | '/teachers/tuitions'
    | '/workers/$id'
    | '/workers/register'
    | '/business/'
    | '/teachers/'
    | '/workers/'
    | '/admin/achievements'
    | '/admin/announcements'
    | '/admin/bills'
    | '/admin/business-categories'
    | '/admin/business-reviews'
    | '/admin/businesses'
    | '/admin/complaints'
    | '/admin/education-news'
    | '/admin/study-resources'
    | '/admin/teachers'
    | '/admin/tuition-applications'
    | '/admin/tuition-requests'
    | '/admin/users'
    | '/admin/workers'
    | '/bills/new'
    | '/api/public/announcements'
    | '/api/public/stats'
    | '/teachers/achievements/$id'
    | '/teachers/news/$id'
    | '/teachers/tuitions/$id'
    | '/teachers/tuitions/new'
    | '/admin/'
    | '/teachers/achievements/'
    | '/teachers/news/'
    | '/teachers/tuitions/'
    | '/bills/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/calculator'
    | '/cv-builder'
    | '/forgot-password'
    | '/helpline'
    | '/isp'
    | '/legal'
    | '/notices'
    | '/reset-password'
    | '/stats'
    | '/utilities'
    | '/bills'
    | '/compare'
    | '/dashboard'
    | '/insights'
    | '/my-business'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/business/$slug'
    | '/business/directory'
    | '/business/register'
    | '/teachers/$id'
    | '/teachers/register'
    | '/teachers/resources'
    | '/workers/$id'
    | '/workers/register'
    | '/business'
    | '/teachers'
    | '/workers'
    | '/admin/achievements'
    | '/admin/announcements'
    | '/admin/bills'
    | '/admin/business-categories'
    | '/admin/business-reviews'
    | '/admin/businesses'
    | '/admin/complaints'
    | '/admin/education-news'
    | '/admin/study-resources'
    | '/admin/teachers'
    | '/admin/tuition-applications'
    | '/admin/tuition-requests'
    | '/admin/users'
    | '/admin/workers'
    | '/bills/new'
    | '/api/public/announcements'
    | '/api/public/stats'
    | '/teachers/achievements/$id'
    | '/teachers/news/$id'
    | '/teachers/tuitions/$id'
    | '/teachers/tuitions/new'
    | '/admin'
    | '/teachers/achievements'
    | '/teachers/news'
    | '/teachers/tuitions'
    | '/bills/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/business'
    | '/calculator'
    | '/cv-builder'
    | '/forgot-password'
    | '/helpline'
    | '/isp'
    | '/legal'
    | '/notices'
    | '/reset-password'
    | '/stats'
    | '/teachers'
    | '/utilities'
    | '/workers'
    | '/_authenticated/admin'
    | '/_authenticated/bills'
    | '/_authenticated/compare'
    | '/_authenticated/dashboard'
    | '/_authenticated/insights'
    | '/_authenticated/my-business'
    | '/_authenticated/profile'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/business/$slug'
    | '/business/directory'
    | '/business/register'
    | '/teachers/$id'
    | '/teachers/achievements'
    | '/teachers/news'
    | '/teachers/register'
    | '/teachers/resources'
    | '/teachers/tuitions'
    | '/workers/$id'
    | '/workers/register'
    | '/business/'
    | '/teachers/'
    | '/workers/'
    | '/_authenticated/admin/achievements'
    | '/_authenticated/admin/announcements'
    | '/_authenticated/admin/bills'
    | '/_authenticated/admin/business-categories'
    | '/_authenticated/admin/business-reviews'
    | '/_authenticated/admin/businesses'
    | '/_authenticated/admin/complaints'
    | '/_authenticated/admin/education-news'
    | '/_authenticated/admin/study-resources'
    | '/_authenticated/admin/teachers'
    | '/_authenticated/admin/tuition-applications'
    | '/_authenticated/admin/tuition-requests'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/workers'
    | '/_authenticated/bills/new'
    | '/api/public/announcements'
    | '/api/public/stats'
    | '/teachers/achievements/$id'
    | '/teachers/news/$id'
    | '/teachers/tuitions/$id'
    | '/teachers/tuitions/new'
    | '/_authenticated/admin/'
    | '/teachers/achievements/'
    | '/teachers/news/'
    | '/teachers/tuitions/'
    | '/_authenticated/bills/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BusinessRoute: typeof BusinessRouteWithChildren
  CalculatorRoute: typeof CalculatorRoute
  CvBuilderRoute: typeof CvBuilderRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HelplineRoute: typeof HelplineRoute
  IspRoute: typeof IspRoute
  LegalRoute: typeof LegalRoute
  NoticesRoute: typeof NoticesRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  StatsRoute: typeof StatsRoute
  TeachersRoute: typeof TeachersRouteWithChildren
  UtilitiesRoute: typeof UtilitiesRoute
  WorkersRoute: typeof WorkersRouteWithChildren
  ApiPublicAnnouncementsRoute: typeof ApiPublicAnnouncementsRoute
  ApiPublicStatsRoute: typeof ApiPublicStatsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workers': {
      id: '/workers'
      path: '/workers'
      fullPath: '/workers'
      preLoaderRoute: typeof WorkersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utilities': {
      id: '/utilities'
      path: '/utilities'
      fullPath: '/utilities'
      preLoaderRoute: typeof UtilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachers': {
      id: '/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof TeachersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notices': {
      id: '/notices'
      path: '/notices'
      fullPath: '/notices'
      preLoaderRoute: typeof NoticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/isp': {
      id: '/isp'
      path: '/isp'
      fullPath: '/isp'
      preLoaderRoute: typeof IspRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/helpline': {
      id: '/helpline'
      path: '/helpline'
      fullPath: '/helpline'
      preLoaderRoute: typeof HelplineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cv-builder': {
      id: '/cv-builder'
      path: '/cv-builder'
      fullPath: '/cv-builder'
      preLoaderRoute: typeof CvBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workers/': {
      id: '/workers/'
      path: '/'
      fullPath: '/workers/'
      preLoaderRoute: typeof WorkersIndexRouteImport
      parentRoute: typeof WorkersRoute
    }
    '/teachers/': {
      id: '/teachers/'
      path: '/'
      fullPath: '/teachers/'
      preLoaderRoute: typeof TeachersIndexRouteImport
      parentRoute: typeof TeachersRoute
    }
    '/business/': {
      id: '/business/'
      path: '/'
      fullPath: '/business/'
      preLoaderRoute: typeof BusinessIndexRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/workers/register': {
      id: '/workers/register'
      path: '/register'
      fullPath: '/workers/register'
      preLoaderRoute: typeof WorkersRegisterRouteImport
      parentRoute: typeof WorkersRoute
    }
    '/workers/$id': {
      id: '/workers/$id'
      path: '/$id'
      fullPath: '/workers/$id'
      preLoaderRoute: typeof WorkersIdRouteImport
      parentRoute: typeof WorkersRoute
    }
    '/teachers/tuitions': {
      id: '/teachers/tuitions'
      path: '/tuitions'
      fullPath: '/teachers/tuitions'
      preLoaderRoute: typeof TeachersTuitionsRouteImport
      parentRoute: typeof TeachersRoute
    }
    '/teachers/resources': {
      id: '/teachers/resources'
      path: '/resources'
      fullPath: '/teachers/resources'
      preLoaderRoute: typeof TeachersResourcesRouteImport
      parentRoute: typeof TeachersRoute
    }
    '/teachers/register': {
      id: '/teachers/register'
      path: '/register'
      fullPath: '/teachers/register'
      preLoaderRoute: typeof TeachersRegisterRouteImport
      parentRoute: typeof TeachersRoute
    }
    '/teachers/news': {
      id: '/teachers/news'
      path: '/news'
      fullPath: '/teachers/news'
      preLoaderRoute: typeof TeachersNewsRouteImport
      parentRoute: typeof TeachersRoute
    }
    '/teachers/achievements': {
      id: '/teachers/achievements'
      path: '/achievements'
      fullPath: '/teachers/achievements'
      preLoaderRoute: typeof TeachersAchievementsRouteImport
      parentRoute: typeof TeachersRoute
    }
    '/teachers/$id': {
      id: '/teachers/$id'
      path: '/$id'
      fullPath: '/teachers/$id'
      preLoaderRoute: typeof TeachersIdRouteImport
      parentRoute: typeof TeachersRoute
    }
    '/business/register': {
      id: '/business/register'
      path: '/register'
      fullPath: '/business/register'
      preLoaderRoute: typeof BusinessRegisterRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/directory': {
      id: '/business/directory'
      path: '/directory'
      fullPath: '/business/directory'
      preLoaderRoute: typeof BusinessDirectoryRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/$slug': {
      id: '/business/$slug'
      path: '/$slug'
      fullPath: '/business/$slug'
      preLoaderRoute: typeof BusinessSlugRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-business': {
      id: '/_authenticated/my-business'
      path: '/my-business'
      fullPath: '/my-business'
      preLoaderRoute: typeof AuthenticatedMyBusinessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/insights': {
      id: '/_authenticated/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AuthenticatedInsightsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compare': {
      id: '/_authenticated/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof AuthenticatedCompareRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bills': {
      id: '/_authenticated/bills'
      path: '/bills'
      fullPath: '/bills'
      preLoaderRoute: typeof AuthenticatedBillsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/teachers/tuitions/': {
      id: '/teachers/tuitions/'
      path: '/'
      fullPath: '/teachers/tuitions/'
      preLoaderRoute: typeof TeachersTuitionsIndexRouteImport
      parentRoute: typeof TeachersTuitionsRoute
    }
    '/teachers/news/': {
      id: '/teachers/news/'
      path: '/'
      fullPath: '/teachers/news/'
      preLoaderRoute: typeof TeachersNewsIndexRouteImport
      parentRoute: typeof TeachersNewsRoute
    }
    '/teachers/achievements/': {
      id: '/teachers/achievements/'
      path: '/'
      fullPath: '/teachers/achievements/'
      preLoaderRoute: typeof TeachersAchievementsIndexRouteImport
      parentRoute: typeof TeachersAchievementsRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/teachers/tuitions/new': {
      id: '/teachers/tuitions/new'
      path: '/new'
      fullPath: '/teachers/tuitions/new'
      preLoaderRoute: typeof TeachersTuitionsNewRouteImport
      parentRoute: typeof TeachersTuitionsRoute
    }
    '/teachers/tuitions/$id': {
      id: '/teachers/tuitions/$id'
      path: '/$id'
      fullPath: '/teachers/tuitions/$id'
      preLoaderRoute: typeof TeachersTuitionsIdRouteImport
      parentRoute: typeof TeachersTuitionsRoute
    }
    '/teachers/news/$id': {
      id: '/teachers/news/$id'
      path: '/$id'
      fullPath: '/teachers/news/$id'
      preLoaderRoute: typeof TeachersNewsIdRouteImport
      parentRoute: typeof TeachersNewsRoute
    }
    '/teachers/achievements/$id': {
      id: '/teachers/achievements/$id'
      path: '/$id'
      fullPath: '/teachers/achievements/$id'
      preLoaderRoute: typeof TeachersAchievementsIdRouteImport
      parentRoute: typeof TeachersAchievementsRoute
    }
    '/api/public/stats': {
      id: '/api/public/stats'
      path: '/api/public/stats'
      fullPath: '/api/public/stats'
      preLoaderRoute: typeof ApiPublicStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/announcements': {
      id: '/api/public/announcements'
      path: '/api/public/announcements'
      fullPath: '/api/public/announcements'
      preLoaderRoute: typeof ApiPublicAnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/bills/new': {
      id: '/_authenticated/bills/new'
      path: '/new'
      fullPath: '/bills/new'
      preLoaderRoute: typeof AuthenticatedBillsNewRouteImport
      parentRoute: typeof AuthenticatedBillsRoute
    }
    '/_authenticated/admin/workers': {
      id: '/_authenticated/admin/workers'
      path: '/workers'
      fullPath: '/admin/workers'
      preLoaderRoute: typeof AuthenticatedAdminWorkersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/tuition-requests': {
      id: '/_authenticated/admin/tuition-requests'
      path: '/tuition-requests'
      fullPath: '/admin/tuition-requests'
      preLoaderRoute: typeof AuthenticatedAdminTuitionRequestsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/tuition-applications': {
      id: '/_authenticated/admin/tuition-applications'
      path: '/tuition-applications'
      fullPath: '/admin/tuition-applications'
      preLoaderRoute: typeof AuthenticatedAdminTuitionApplicationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/teachers': {
      id: '/_authenticated/admin/teachers'
      path: '/teachers'
      fullPath: '/admin/teachers'
      preLoaderRoute: typeof AuthenticatedAdminTeachersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/study-resources': {
      id: '/_authenticated/admin/study-resources'
      path: '/study-resources'
      fullPath: '/admin/study-resources'
      preLoaderRoute: typeof AuthenticatedAdminStudyResourcesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/education-news': {
      id: '/_authenticated/admin/education-news'
      path: '/education-news'
      fullPath: '/admin/education-news'
      preLoaderRoute: typeof AuthenticatedAdminEducationNewsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/complaints': {
      id: '/_authenticated/admin/complaints'
      path: '/complaints'
      fullPath: '/admin/complaints'
      preLoaderRoute: typeof AuthenticatedAdminComplaintsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/businesses': {
      id: '/_authenticated/admin/businesses'
      path: '/businesses'
      fullPath: '/admin/businesses'
      preLoaderRoute: typeof AuthenticatedAdminBusinessesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/business-reviews': {
      id: '/_authenticated/admin/business-reviews'
      path: '/business-reviews'
      fullPath: '/admin/business-reviews'
      preLoaderRoute: typeof AuthenticatedAdminBusinessReviewsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/business-categories': {
      id: '/_authenticated/admin/business-categories'
      path: '/business-categories'
      fullPath: '/admin/business-categories'
      preLoaderRoute: typeof AuthenticatedAdminBusinessCategoriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/bills': {
      id: '/_authenticated/admin/bills'
      path: '/bills'
      fullPath: '/admin/bills'
      preLoaderRoute: typeof AuthenticatedAdminBillsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/announcements': {
      id: '/_authenticated/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AuthenticatedAdminAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/achievements': {
      id: '/_authenticated/admin/achievements'
      path: '/achievements'
      fullPath: '/admin/achievements'
      preLoaderRoute: typeof AuthenticatedAdminAchievementsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/bills/$id/edit': {
      id: '/_authenticated/bills/$id/edit'
      path: '/$id/edit'
      fullPath: '/bills/$id/edit'
      preLoaderRoute: typeof AuthenticatedBillsIdEditRouteImport
      parentRoute: typeof AuthenticatedBillsRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAchievementsRoute: typeof AuthenticatedAdminAchievementsRoute
  AuthenticatedAdminAnnouncementsRoute: typeof AuthenticatedAdminAnnouncementsRoute
  AuthenticatedAdminBillsRoute: typeof AuthenticatedAdminBillsRoute
  AuthenticatedAdminBusinessCategoriesRoute: typeof AuthenticatedAdminBusinessCategoriesRoute
  AuthenticatedAdminBusinessReviewsRoute: typeof AuthenticatedAdminBusinessReviewsRoute
  AuthenticatedAdminBusinessesRoute: typeof AuthenticatedAdminBusinessesRoute
  AuthenticatedAdminComplaintsRoute: typeof AuthenticatedAdminComplaintsRoute
  AuthenticatedAdminEducationNewsRoute: typeof AuthenticatedAdminEducationNewsRoute
  AuthenticatedAdminStudyResourcesRoute: typeof AuthenticatedAdminStudyResourcesRoute
  AuthenticatedAdminTeachersRoute: typeof AuthenticatedAdminTeachersRoute
  AuthenticatedAdminTuitionApplicationsRoute: typeof AuthenticatedAdminTuitionApplicationsRoute
  AuthenticatedAdminTuitionRequestsRoute: typeof AuthenticatedAdminTuitionRequestsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminWorkersRoute: typeof AuthenticatedAdminWorkersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAchievementsRoute: AuthenticatedAdminAchievementsRoute,
  AuthenticatedAdminAnnouncementsRoute: AuthenticatedAdminAnnouncementsRoute,
  AuthenticatedAdminBillsRoute: AuthenticatedAdminBillsRoute,
  AuthenticatedAdminBusinessCategoriesRoute:
    AuthenticatedAdminBusinessCategoriesRoute,
  AuthenticatedAdminBusinessReviewsRoute:
    AuthenticatedAdminBusinessReviewsRoute,
  AuthenticatedAdminBusinessesRoute: AuthenticatedAdminBusinessesRoute,
  AuthenticatedAdminComplaintsRoute: AuthenticatedAdminComplaintsRoute,
  AuthenticatedAdminEducationNewsRoute: AuthenticatedAdminEducationNewsRoute,
  AuthenticatedAdminStudyResourcesRoute: AuthenticatedAdminStudyResourcesRoute,
  AuthenticatedAdminTeachersRoute: AuthenticatedAdminTeachersRoute,
  AuthenticatedAdminTuitionApplicationsRoute:
    AuthenticatedAdminTuitionApplicationsRoute,
  AuthenticatedAdminTuitionRequestsRoute:
    AuthenticatedAdminTuitionRequestsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminWorkersRoute: AuthenticatedAdminWorkersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedBillsRouteChildren {
  AuthenticatedBillsNewRoute: typeof AuthenticatedBillsNewRoute
  AuthenticatedBillsIdEditRoute: typeof AuthenticatedBillsIdEditRoute
}

const AuthenticatedBillsRouteChildren: AuthenticatedBillsRouteChildren = {
  AuthenticatedBillsNewRoute: AuthenticatedBillsNewRoute,
  AuthenticatedBillsIdEditRoute: AuthenticatedBillsIdEditRoute,
}

const AuthenticatedBillsRouteWithChildren =
  AuthenticatedBillsRoute._addFileChildren(AuthenticatedBillsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedBillsRoute: typeof AuthenticatedBillsRouteWithChildren
  AuthenticatedCompareRoute: typeof AuthenticatedCompareRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInsightsRoute: typeof AuthenticatedInsightsRoute
  AuthenticatedMyBusinessRoute: typeof AuthenticatedMyBusinessRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedBillsRoute: AuthenticatedBillsRouteWithChildren,
  AuthenticatedCompareRoute: AuthenticatedCompareRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInsightsRoute: AuthenticatedInsightsRoute,
  AuthenticatedMyBusinessRoute: AuthenticatedMyBusinessRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface BusinessRouteChildren {
  BusinessSlugRoute: typeof BusinessSlugRoute
  BusinessDirectoryRoute: typeof BusinessDirectoryRoute
  BusinessRegisterRoute: typeof BusinessRegisterRoute
  BusinessIndexRoute: typeof BusinessIndexRoute
}

const BusinessRouteChildren: BusinessRouteChildren = {
  BusinessSlugRoute: BusinessSlugRoute,
  BusinessDirectoryRoute: BusinessDirectoryRoute,
  BusinessRegisterRoute: BusinessRegisterRoute,
  BusinessIndexRoute: BusinessIndexRoute,
}

const BusinessRouteWithChildren = BusinessRoute._addFileChildren(
  BusinessRouteChildren,
)

interface TeachersAchievementsRouteChildren {
  TeachersAchievementsIdRoute: typeof TeachersAchievementsIdRoute
  TeachersAchievementsIndexRoute: typeof TeachersAchievementsIndexRoute
}

const TeachersAchievementsRouteChildren: TeachersAchievementsRouteChildren = {
  TeachersAchievementsIdRoute: TeachersAchievementsIdRoute,
  TeachersAchievementsIndexRoute: TeachersAchievementsIndexRoute,
}

const TeachersAchievementsRouteWithChildren =
  TeachersAchievementsRoute._addFileChildren(TeachersAchievementsRouteChildren)

interface TeachersNewsRouteChildren {
  TeachersNewsIdRoute: typeof TeachersNewsIdRoute
  TeachersNewsIndexRoute: typeof TeachersNewsIndexRoute
}

const TeachersNewsRouteChildren: TeachersNewsRouteChildren = {
  TeachersNewsIdRoute: TeachersNewsIdRoute,
  TeachersNewsIndexRoute: TeachersNewsIndexRoute,
}

const TeachersNewsRouteWithChildren = TeachersNewsRoute._addFileChildren(
  TeachersNewsRouteChildren,
)

interface TeachersTuitionsRouteChildren {
  TeachersTuitionsIdRoute: typeof TeachersTuitionsIdRoute
  TeachersTuitionsNewRoute: typeof TeachersTuitionsNewRoute
  TeachersTuitionsIndexRoute: typeof TeachersTuitionsIndexRoute
}

const TeachersTuitionsRouteChildren: TeachersTuitionsRouteChildren = {
  TeachersTuitionsIdRoute: TeachersTuitionsIdRoute,
  TeachersTuitionsNewRoute: TeachersTuitionsNewRoute,
  TeachersTuitionsIndexRoute: TeachersTuitionsIndexRoute,
}

const TeachersTuitionsRouteWithChildren =
  TeachersTuitionsRoute._addFileChildren(TeachersTuitionsRouteChildren)

interface TeachersRouteChildren {
  TeachersIdRoute: typeof TeachersIdRoute
  TeachersAchievementsRoute: typeof TeachersAchievementsRouteWithChildren
  TeachersNewsRoute: typeof TeachersNewsRouteWithChildren
  TeachersRegisterRoute: typeof TeachersRegisterRoute
  TeachersResourcesRoute: typeof TeachersResourcesRoute
  TeachersTuitionsRoute: typeof TeachersTuitionsRouteWithChildren
  TeachersIndexRoute: typeof TeachersIndexRoute
}

const TeachersRouteChildren: TeachersRouteChildren = {
  TeachersIdRoute: TeachersIdRoute,
  TeachersAchievementsRoute: TeachersAchievementsRouteWithChildren,
  TeachersNewsRoute: TeachersNewsRouteWithChildren,
  TeachersRegisterRoute: TeachersRegisterRoute,
  TeachersResourcesRoute: TeachersResourcesRoute,
  TeachersTuitionsRoute: TeachersTuitionsRouteWithChildren,
  TeachersIndexRoute: TeachersIndexRoute,
}

const TeachersRouteWithChildren = TeachersRoute._addFileChildren(
  TeachersRouteChildren,
)

interface WorkersRouteChildren {
  WorkersIdRoute: typeof WorkersIdRoute
  WorkersRegisterRoute: typeof WorkersRegisterRoute
  WorkersIndexRoute: typeof WorkersIndexRoute
}

const WorkersRouteChildren: WorkersRouteChildren = {
  WorkersIdRoute: WorkersIdRoute,
  WorkersRegisterRoute: WorkersRegisterRoute,
  WorkersIndexRoute: WorkersIndexRoute,
}

const WorkersRouteWithChildren =
  WorkersRoute._addFileChildren(WorkersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BusinessRoute: BusinessRouteWithChildren,
  CalculatorRoute: CalculatorRoute,
  CvBuilderRoute: CvBuilderRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HelplineRoute: HelplineRoute,
  IspRoute: IspRoute,
  LegalRoute: LegalRoute,
  NoticesRoute: NoticesRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  StatsRoute: StatsRoute,
  TeachersRoute: TeachersRouteWithChildren,
  UtilitiesRoute: UtilitiesRoute,
  WorkersRoute: WorkersRouteWithChildren,
  ApiPublicAnnouncementsRoute: ApiPublicAnnouncementsRoute,
  ApiPublicStatsRoute: ApiPublicStatsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
