/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkersRouteImport } from './routes/workers'
import { Route as UtilitiesRouteImport } from './routes/utilities'
import { Route as TeachersRouteImport } from './routes/teachers'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as NoticesRouteImport } from './routes/notices'
import { Route as IspRouteImport } from './routes/isp'
import { Route as HelplineRouteImport } from './routes/helpline'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CvBuilderRouteImport } from './routes/cv-builder'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkersIndexRouteImport } from './routes/workers.index'
import { Route as TeachersIndexRouteImport } from './routes/teachers.index'
import { Route as WorkersRegisterRouteImport } from './routes/workers.register'
import { Route as WorkersIdRouteImport } from './routes/workers.$id'
import { Route as TeachersRegisterRouteImport } from './routes/teachers.register'
import { Route as TeachersIdRouteImport } from './routes/teachers.$id'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedInsightsRouteImport } from './routes/_authenticated/insights'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCompareRouteImport } from './routes/_authenticated/compare'
import { Route as AuthenticatedBillsRouteImport } from './routes/_authenticated/bills'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as ApiPublicStatsRouteImport } from './routes/api/public/stats'
import { Route as ApiPublicAnnouncementsRouteImport } from './routes/api/public/announcements'
import { Route as AuthenticatedBillsNewRouteImport } from './routes/_authenticated/bills.new'
import { Route as AuthenticatedAdminWorkersRouteImport } from './routes/_authenticated/admin.workers'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminComplaintsRouteImport } from './routes/_authenticated/admin.complaints'
import { Route as AuthenticatedAdminBillsRouteImport } from './routes/_authenticated/admin.bills'
import { Route as AuthenticatedAdminAnnouncementsRouteImport } from './routes/_authenticated/admin.announcements'
import { Route as AuthenticatedBillsIdEditRouteImport } from './routes/_authenticated/bills.$id.edit'

const WorkersRoute = WorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => rootRouteImport,
} as any)
const UtilitiesRoute = UtilitiesRouteImport.update({
  id: '/utilities',
  path: '/utilities',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachersRoute = TeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticesRoute = NoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => rootRouteImport,
} as any)
const IspRoute = IspRouteImport.update({
  id: '/isp',
  path: '/isp',
  getParentRoute: () => rootRouteImport,
} as any)
const HelplineRoute = HelplineRouteImport.update({
  id: '/helpline',
  path: '/helpline',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CvBuilderRoute = CvBuilderRouteImport.update({
  id: '/cv-builder',
  path: '/cv-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkersIndexRoute = WorkersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkersRoute,
} as any)
const TeachersIndexRoute = TeachersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeachersRoute,
} as any)
const WorkersRegisterRoute = WorkersRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => WorkersRoute,
} as any)
const WorkersIdRoute = WorkersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => WorkersRoute,
} as any)
const TeachersRegisterRoute = TeachersRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => TeachersRoute,
} as any)
const TeachersIdRoute = TeachersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TeachersRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInsightsRoute = AuthenticatedInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompareRoute = AuthenticatedCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillsRoute = AuthenticatedBillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiPublicStatsRoute = ApiPublicStatsRouteImport.update({
  id: '/api/public/stats',
  path: '/api/public/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAnnouncementsRoute = ApiPublicAnnouncementsRouteImport.update({
  id: '/api/public/announcements',
  path: '/api/public/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBillsNewRoute = AuthenticatedBillsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedBillsRoute,
} as any)
const AuthenticatedAdminWorkersRoute =
  AuthenticatedAdminWorkersRouteImport.update({
    id: '/workers',
    path: '/workers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminComplaintsRoute =
  AuthenticatedAdminComplaintsRouteImport.update({
    id: '/complaints',
    path: '/complaints',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBillsRoute = AuthenticatedAdminBillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAnnouncementsRoute =
  AuthenticatedAdminAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedBillsIdEditRoute =
  AuthenticatedBillsIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => AuthenticatedBillsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calculator': typeof CalculatorRoute
  '/cv-builder': typeof CvBuilderRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/helpline': typeof HelplineRoute
  '/isp': typeof IspRoute
  '/notices': typeof NoticesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/stats': typeof StatsRoute
  '/teachers': typeof TeachersRouteWithChildren
  '/utilities': typeof UtilitiesRoute
  '/workers': typeof WorkersRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/bills': typeof AuthenticatedBillsRouteWithChildren
  '/compare': typeof AuthenticatedCompareRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/teachers/$id': typeof TeachersIdRoute
  '/teachers/register': typeof TeachersRegisterRoute
  '/workers/$id': typeof WorkersIdRoute
  '/workers/register': typeof WorkersRegisterRoute
  '/teachers/': typeof TeachersIndexRoute
  '/workers/': typeof WorkersIndexRoute
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/bills': typeof AuthenticatedAdminBillsRoute
  '/admin/complaints': typeof AuthenticatedAdminComplaintsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/workers': typeof AuthenticatedAdminWorkersRoute
  '/bills/new': typeof AuthenticatedBillsNewRoute
  '/api/public/announcements': typeof ApiPublicAnnouncementsRoute
  '/api/public/stats': typeof ApiPublicStatsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/bills/$id/edit': typeof AuthenticatedBillsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calculator': typeof CalculatorRoute
  '/cv-builder': typeof CvBuilderRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/helpline': typeof HelplineRoute
  '/isp': typeof IspRoute
  '/notices': typeof NoticesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/stats': typeof StatsRoute
  '/utilities': typeof UtilitiesRoute
  '/bills': typeof AuthenticatedBillsRouteWithChildren
  '/compare': typeof AuthenticatedCompareRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/teachers/$id': typeof TeachersIdRoute
  '/teachers/register': typeof TeachersRegisterRoute
  '/workers/$id': typeof WorkersIdRoute
  '/workers/register': typeof WorkersRegisterRoute
  '/teachers': typeof TeachersIndexRoute
  '/workers': typeof WorkersIndexRoute
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/bills': typeof AuthenticatedAdminBillsRoute
  '/admin/complaints': typeof AuthenticatedAdminComplaintsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/workers': typeof AuthenticatedAdminWorkersRoute
  '/bills/new': typeof AuthenticatedBillsNewRoute
  '/api/public/announcements': typeof ApiPublicAnnouncementsRoute
  '/api/public/stats': typeof ApiPublicStatsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/bills/$id/edit': typeof AuthenticatedBillsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/calculator': typeof CalculatorRoute
  '/cv-builder': typeof CvBuilderRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/helpline': typeof HelplineRoute
  '/isp': typeof IspRoute
  '/notices': typeof NoticesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/stats': typeof StatsRoute
  '/teachers': typeof TeachersRouteWithChildren
  '/utilities': typeof UtilitiesRoute
  '/workers': typeof WorkersRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/bills': typeof AuthenticatedBillsRouteWithChildren
  '/_authenticated/compare': typeof AuthenticatedCompareRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/insights': typeof AuthenticatedInsightsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/teachers/$id': typeof TeachersIdRoute
  '/teachers/register': typeof TeachersRegisterRoute
  '/workers/$id': typeof WorkersIdRoute
  '/workers/register': typeof WorkersRegisterRoute
  '/teachers/': typeof TeachersIndexRoute
  '/workers/': typeof WorkersIndexRoute
  '/_authenticated/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/_authenticated/admin/bills': typeof AuthenticatedAdminBillsRoute
  '/_authenticated/admin/complaints': typeof AuthenticatedAdminComplaintsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/workers': typeof AuthenticatedAdminWorkersRoute
  '/_authenticated/bills/new': typeof AuthenticatedBillsNewRoute
  '/api/public/announcements': typeof ApiPublicAnnouncementsRoute
  '/api/public/stats': typeof ApiPublicStatsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/bills/$id/edit': typeof AuthenticatedBillsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/calculator'
    | '/cv-builder'
    | '/forgot-password'
    | '/helpline'
    | '/isp'
    | '/notices'
    | '/reset-password'
    | '/stats'
    | '/teachers'
    | '/utilities'
    | '/workers'
    | '/admin'
    | '/bills'
    | '/compare'
    | '/dashboard'
    | '/insights'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/teachers/$id'
    | '/teachers/register'
    | '/workers/$id'
    | '/workers/register'
    | '/teachers/'
    | '/workers/'
    | '/admin/announcements'
    | '/admin/bills'
    | '/admin/complaints'
    | '/admin/users'
    | '/admin/workers'
    | '/bills/new'
    | '/api/public/announcements'
    | '/api/public/stats'
    | '/admin/'
    | '/bills/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/calculator'
    | '/cv-builder'
    | '/forgot-password'
    | '/helpline'
    | '/isp'
    | '/notices'
    | '/reset-password'
    | '/stats'
    | '/utilities'
    | '/bills'
    | '/compare'
    | '/dashboard'
    | '/insights'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/teachers/$id'
    | '/teachers/register'
    | '/workers/$id'
    | '/workers/register'
    | '/teachers'
    | '/workers'
    | '/admin/announcements'
    | '/admin/bills'
    | '/admin/complaints'
    | '/admin/users'
    | '/admin/workers'
    | '/bills/new'
    | '/api/public/announcements'
    | '/api/public/stats'
    | '/admin'
    | '/bills/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/calculator'
    | '/cv-builder'
    | '/forgot-password'
    | '/helpline'
    | '/isp'
    | '/notices'
    | '/reset-password'
    | '/stats'
    | '/teachers'
    | '/utilities'
    | '/workers'
    | '/_authenticated/admin'
    | '/_authenticated/bills'
    | '/_authenticated/compare'
    | '/_authenticated/dashboard'
    | '/_authenticated/insights'
    | '/_authenticated/profile'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/teachers/$id'
    | '/teachers/register'
    | '/workers/$id'
    | '/workers/register'
    | '/teachers/'
    | '/workers/'
    | '/_authenticated/admin/announcements'
    | '/_authenticated/admin/bills'
    | '/_authenticated/admin/complaints'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/workers'
    | '/_authenticated/bills/new'
    | '/api/public/announcements'
    | '/api/public/stats'
    | '/_authenticated/admin/'
    | '/_authenticated/bills/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CalculatorRoute: typeof CalculatorRoute
  CvBuilderRoute: typeof CvBuilderRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HelplineRoute: typeof HelplineRoute
  IspRoute: typeof IspRoute
  NoticesRoute: typeof NoticesRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  StatsRoute: typeof StatsRoute
  TeachersRoute: typeof TeachersRouteWithChildren
  UtilitiesRoute: typeof UtilitiesRoute
  WorkersRoute: typeof WorkersRouteWithChildren
  ApiPublicAnnouncementsRoute: typeof ApiPublicAnnouncementsRoute
  ApiPublicStatsRoute: typeof ApiPublicStatsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workers': {
      id: '/workers'
      path: '/workers'
      fullPath: '/workers'
      preLoaderRoute: typeof WorkersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utilities': {
      id: '/utilities'
      path: '/utilities'
      fullPath: '/utilities'
      preLoaderRoute: typeof UtilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachers': {
      id: '/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof TeachersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notices': {
      id: '/notices'
      path: '/notices'
      fullPath: '/notices'
      preLoaderRoute: typeof NoticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/isp': {
      id: '/isp'
      path: '/isp'
      fullPath: '/isp'
      preLoaderRoute: typeof IspRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/helpline': {
      id: '/helpline'
      path: '/helpline'
      fullPath: '/helpline'
      preLoaderRoute: typeof HelplineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cv-builder': {
      id: '/cv-builder'
      path: '/cv-builder'
      fullPath: '/cv-builder'
      preLoaderRoute: typeof CvBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workers/': {
      id: '/workers/'
      path: '/'
      fullPath: '/workers/'
      preLoaderRoute: typeof WorkersIndexRouteImport
      parentRoute: typeof WorkersRoute
    }
    '/teachers/': {
      id: '/teachers/'
      path: '/'
      fullPath: '/teachers/'
      preLoaderRoute: typeof TeachersIndexRouteImport
      parentRoute: typeof TeachersRoute
    }
    '/workers/register': {
      id: '/workers/register'
      path: '/register'
      fullPath: '/workers/register'
      preLoaderRoute: typeof WorkersRegisterRouteImport
      parentRoute: typeof WorkersRoute
    }
    '/workers/$id': {
      id: '/workers/$id'
      path: '/$id'
      fullPath: '/workers/$id'
      preLoaderRoute: typeof WorkersIdRouteImport
      parentRoute: typeof WorkersRoute
    }
    '/teachers/register': {
      id: '/teachers/register'
      path: '/register'
      fullPath: '/teachers/register'
      preLoaderRoute: typeof TeachersRegisterRouteImport
      parentRoute: typeof TeachersRoute
    }
    '/teachers/$id': {
      id: '/teachers/$id'
      path: '/$id'
      fullPath: '/teachers/$id'
      preLoaderRoute: typeof TeachersIdRouteImport
      parentRoute: typeof TeachersRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/insights': {
      id: '/_authenticated/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AuthenticatedInsightsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compare': {
      id: '/_authenticated/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof AuthenticatedCompareRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bills': {
      id: '/_authenticated/bills'
      path: '/bills'
      fullPath: '/bills'
      preLoaderRoute: typeof AuthenticatedBillsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/stats': {
      id: '/api/public/stats'
      path: '/api/public/stats'
      fullPath: '/api/public/stats'
      preLoaderRoute: typeof ApiPublicStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/announcements': {
      id: '/api/public/announcements'
      path: '/api/public/announcements'
      fullPath: '/api/public/announcements'
      preLoaderRoute: typeof ApiPublicAnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/bills/new': {
      id: '/_authenticated/bills/new'
      path: '/new'
      fullPath: '/bills/new'
      preLoaderRoute: typeof AuthenticatedBillsNewRouteImport
      parentRoute: typeof AuthenticatedBillsRoute
    }
    '/_authenticated/admin/workers': {
      id: '/_authenticated/admin/workers'
      path: '/workers'
      fullPath: '/admin/workers'
      preLoaderRoute: typeof AuthenticatedAdminWorkersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/complaints': {
      id: '/_authenticated/admin/complaints'
      path: '/complaints'
      fullPath: '/admin/complaints'
      preLoaderRoute: typeof AuthenticatedAdminComplaintsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/bills': {
      id: '/_authenticated/admin/bills'
      path: '/bills'
      fullPath: '/admin/bills'
      preLoaderRoute: typeof AuthenticatedAdminBillsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/announcements': {
      id: '/_authenticated/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AuthenticatedAdminAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/bills/$id/edit': {
      id: '/_authenticated/bills/$id/edit'
      path: '/$id/edit'
      fullPath: '/bills/$id/edit'
      preLoaderRoute: typeof AuthenticatedBillsIdEditRouteImport
      parentRoute: typeof AuthenticatedBillsRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAnnouncementsRoute: typeof AuthenticatedAdminAnnouncementsRoute
  AuthenticatedAdminBillsRoute: typeof AuthenticatedAdminBillsRoute
  AuthenticatedAdminComplaintsRoute: typeof AuthenticatedAdminComplaintsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminWorkersRoute: typeof AuthenticatedAdminWorkersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAnnouncementsRoute: AuthenticatedAdminAnnouncementsRoute,
  AuthenticatedAdminBillsRoute: AuthenticatedAdminBillsRoute,
  AuthenticatedAdminComplaintsRoute: AuthenticatedAdminComplaintsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminWorkersRoute: AuthenticatedAdminWorkersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedBillsRouteChildren {
  AuthenticatedBillsNewRoute: typeof AuthenticatedBillsNewRoute
  AuthenticatedBillsIdEditRoute: typeof AuthenticatedBillsIdEditRoute
}

const AuthenticatedBillsRouteChildren: AuthenticatedBillsRouteChildren = {
  AuthenticatedBillsNewRoute: AuthenticatedBillsNewRoute,
  AuthenticatedBillsIdEditRoute: AuthenticatedBillsIdEditRoute,
}

const AuthenticatedBillsRouteWithChildren =
  AuthenticatedBillsRoute._addFileChildren(AuthenticatedBillsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedBillsRoute: typeof AuthenticatedBillsRouteWithChildren
  AuthenticatedCompareRoute: typeof AuthenticatedCompareRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInsightsRoute: typeof AuthenticatedInsightsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedBillsRoute: AuthenticatedBillsRouteWithChildren,
  AuthenticatedCompareRoute: AuthenticatedCompareRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInsightsRoute: AuthenticatedInsightsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface TeachersRouteChildren {
  TeachersIdRoute: typeof TeachersIdRoute
  TeachersRegisterRoute: typeof TeachersRegisterRoute
  TeachersIndexRoute: typeof TeachersIndexRoute
}

const TeachersRouteChildren: TeachersRouteChildren = {
  TeachersIdRoute: TeachersIdRoute,
  TeachersRegisterRoute: TeachersRegisterRoute,
  TeachersIndexRoute: TeachersIndexRoute,
}

const TeachersRouteWithChildren = TeachersRoute._addFileChildren(
  TeachersRouteChildren,
)

interface WorkersRouteChildren {
  WorkersIdRoute: typeof WorkersIdRoute
  WorkersRegisterRoute: typeof WorkersRegisterRoute
  WorkersIndexRoute: typeof WorkersIndexRoute
}

const WorkersRouteChildren: WorkersRouteChildren = {
  WorkersIdRoute: WorkersIdRoute,
  WorkersRegisterRoute: WorkersRegisterRoute,
  WorkersIndexRoute: WorkersIndexRoute,
}

const WorkersRouteWithChildren =
  WorkersRoute._addFileChildren(WorkersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CalculatorRoute: CalculatorRoute,
  CvBuilderRoute: CvBuilderRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HelplineRoute: HelplineRoute,
  IspRoute: IspRoute,
  NoticesRoute: NoticesRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  StatsRoute: StatsRoute,
  TeachersRoute: TeachersRouteWithChildren,
  UtilitiesRoute: UtilitiesRoute,
  WorkersRoute: WorkersRouteWithChildren,
  ApiPublicAnnouncementsRoute: ApiPublicAnnouncementsRoute,
  ApiPublicStatsRoute: ApiPublicStatsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
